server:
  port: 8080
eureka:
 client:
   service-url:
    defaultZone: http://localhost:8761/eureka/
spring:
 application:
  name: APIGateWay
 cloud:
    gateway:
      routes:
      - id: courseModule
        uri: http://localhost:8081/
        predicates:
        - Path=/course/**
        
      - id: feedbackModule
        uri: http://localhost:8082/
        predicates:
         - Path=/feedback/**
       
        
      - id: userModule
        uri: http://localhost:8083/
        predicates:
        - Path=/user/**
        
      - id: loginModule
        uri: http://localhost:8090/
        predicates:
        - Path=/login/**
        
      - id: paymentModule
        uri: http://localhost:8084/
        predicates:
        - Path=/payment/**
        
        
       